### ISSUE TITLE
Got ecma interpreter exception.

### ISSUE THREAD

**Issue by 2770862886** [JVoiceXML/JVoiceXML#146]
2022-03-29 18:34:37.410 3737-3831/? W/System.err: Caused by: java.lang.UnsupportedOperationException: can't load this type of class file
2022-03-29 18:34:37.410 3737-3831/? W/System.err:     at java.lang.ClassLoader.defineClass(ClassLoader.java:591)
2022-03-29 18:34:37.410 3737-3831/? W/System.err:     at org.mozilla.javascript.DefiningClassLoader.defineClass(DefiningClassLoader.java:62)
2022-03-29 18:34:37.410 3737-3831/? W/System.err:     at org.mozilla.javascript.optimizer.Codegen.defineClass(Codegen.java:146)
2022-03-29 18:34:37.410 3737-3831/? W/System.err:     at org.mozilla.javascript.optimizer.Codegen.createScriptObject(Codegen.java:101)
2022-03-29 18:34:37.410 3737-3831/? W/System.err:     at org.mozilla.javascript.Context.compileImpl(Context.java:2409)
2022-03-29 18:34:37.411 3737-3831/? W/System.err:     at org.mozilla.javascript.Context.compileString(Context.java:1359)
2022-03-29 18:34:37.411 3737-3831/? W/System.err:     at org.mozilla.javascript.Context.compileString(Context.java:1348)
2022-03-29 18:34:37.411 3737-3831/? W/System.err:     at org.mozilla.javascript.Context.evaluateString(Context.java:1101)
2022-03-29 18:34:37.411 3737-3831/? W/System.err:     at org.jvoicexml.interpreter.datamodel.ecmascript.EcmaScriptDataModel.evaluateExpression(EcmaScriptDataModel.java:1008)
2022-03-29 18:34:37.411 3737-3831/? W/System.err:     at org.jvoicexml.interpreter.datamodel.ecmascript.EcmaScriptDataModel.evaluateExpression(EcmaScriptDataModel.java:976)
2022-03-29 18:34:37.411 3737-3831/? W/System.err:     at org.jvoicexml.interpreter.PromptChooser.filterCond(PromptChooser.java:172)
2022-03-29 18:34:37.411 3737-3831/? W/System.err:     at org.jvoicexml.interpreter.PromptChooser.collect(PromptChooser.java:105)
2022-03-29 18:34:37.411 3737-3831/? W/System.err:     at org.jvoicexml.interpreter.FormInterpretationAlgorithm.queuePrompts(FormInterpretationAlgorithm.java:911)
2022-03-29 18:34:37.412 3737-3831/? W/System.err:     at org.jvoicexml.interpreter.FormInterpretationAlgorithm.collect(FormInterpretationAlgorithm.java:718)
2022-03-29 18:34:37.412 3737-3831/? W/System.err:     at org.jvoicexml.interpreter.FormInterpretationAlgorithm.mainLoop(FormInterpretationAlgorithm.java:487)
2022-03-29 18:34:37.412 3737-3831/? W/System.err:     at org.jvoicexml.interpreter.VoiceXmlInterpreter.process(VoiceXmlInterpreter.java:255)
2022-03-29 18:34:37.412 3737-3831/? W/System.err:     at org.jvoicexml.interpreter.VoiceXmlInterpreterContext.interpret(VoiceXmlInterpreterContext.java:795)
2022-03-29 18:34:37.412 3737-3831/? W/System.err:     at org.jvoicexml.interpreter.VoiceXmlInterpreterContext.process(VoiceXmlInterpreterContext.java:459)
2022-03-29 18:34:37.412 3737-3831/? W/System.err:     at org.jvoicexml.interpreter.JVoiceXmlSession.run(JVoiceXmlSession.java:407)

with vxml:
`<?xml version="1.0" encoding="UTF-8"?>
<vxml xmlns="http://www.w3.org/2001/vxml" version="2.1">
  <form id="get_address">
    <field name="country">
      <grammar type="application/srgs+xml" src="country.grxml"/>
      <prompt>Say a country.</prompt>
    </field>

    <field name="city">
      <grammar type="application/srgs+xml" srcexpr="country + '/cities.grxml'"/>
      <prompt>What city in.</prompt>
    </field>

    <field name="street">
      <grammar type="application/srgs+xml" srcexpr="country + '/' + city + '/streets.grxml'"/>
      <prompt> What street in  are you looking for? </prompt>
    </field>
  </form>
</vxml>
`

**Comment by 2770862886** [comment]
with the test vxml:

<?xml version="1.0" encoding="UTF-8"?>
<vxml xmlns="http://www.w3.org/2001/vxml" version="2.1">
  <form id="get_address">
    <field name="country">
      <grammar type="application/srgs+xml" src="country.grxml"/>
      <prompt>Say a country.</prompt>
    </field>

    <field name="city">
      <grammar type="application/srgs+xml" srcexpr="country + '/cities.grxml'"/>
      <prompt>What city in <value expr="country"/>.</prompt>
    </field>

    <field name="street">
      <grammar type="application/srgs+xml" srcexpr="country + '/' + city + '/streets.grxml'"/>
      <prompt> What street in <value expr="city"/> are you looking for? </prompt>
    </field>
  </form>
</vxml>

**Comment by schnelle** [comment]
Could you please provide the following info
- Version of JVoiceXML
- Java version

**Comment by schnelle** [comment]
Closed as there was no reply for > 1 month.
