### ISSUE TITLE
Exception Occurred while read external xml grammar

### ISSUE THREAD

**Issue by 2770862886** [JVoiceXML/JVoiceXML#147]
2022-04-07 03:43:13.851 7017-7126/com.example.voicetester W/System.err: Caused by: java.lang.ClassCastException: org.apache.harmony.xml.dom.DocumentImpl cannot be cast to org.jvoicexml.documentserver.ReadBuffer
2022-04-07 03:43:13.851 7017-7126/com.example.voicetester W/System.err:     at com.ebanma.speech.callmanager.DocumentServer.getGrammarDocument(DocumentServer.java:159)
2022-04-07 03:43:13.851 7017-7126/com.example.voicetester W/System.err:     at org.jvoicexml.interpreter.VoiceXmlInterpreterContext.acquireExternalGrammar(VoiceXmlInterpreterContext.java:754)
2022-04-07 03:43:13.852 7017-7126/com.example.voicetester W/System.err:     at org.jvoicexml.interpreter.grammar.GrammarLoader.loadExternalGrammar(GrammarLoader.java:203)
2022-04-07 03:43:13.852 7017-7126/com.example.voicetester W/System.err:     at org.jvoicexml.interpreter.grammar.GrammarLoader.loadGrammarDocument(GrammarLoader.java:85)
2022-04-07 03:43:13.853 7017-7126/com.example.voicetester W/System.err:     at org.jvoicexml.interpreter.grammar.JVoiceXmlGrammarProcessor.process(JVoiceXmlGrammarProcessor.java:105)
2022-04-07 03:43:13.853 7017-7126/com.example.voicetester W/System.err:     at org.jvoicexml.interpreter.FormInterpretationAlgorithm.processGrammar(FormInterpretationAlgorithm.java:1025)
2022-04-07 03:43:13.853 7017-7126/com.example.voicetester W/System.err:     at org.jvoicexml.interpreter.FormInterpretationAlgorithm.processGrammars(FormInterpretationAlgorithm.java:1069)
2022-04-07 03:43:13.854 7017-7126/com.example.voicetester W/System.err:     at org.jvoicexml.interpreter.FormInterpretationAlgorithm.activateGrammars(FormInterpretationAlgorithm.java:1206)
2022-04-07 03:43:13.854 7017-7126/com.example.voicetester W/System.err:     at org.jvoicexml.interpreter.FormInterpretationAlgorithm.collect(FormInterpretationAlgorithm.java:735)
2022-04-07 03:43:13.855 7017-7126/com.example.voicetester W/System.err:     at org.jvoicexml.interpreter.FormInterpretationAlgorithm.mainLoop(FormInterpretationAlgorithm.java:487)
2022-04-07 03:43:13.855 7017-7126/com.example.voicetester W/System.err:     at org.jvoicexml.interpreter.VoiceXmlInterpreter.process(VoiceXmlInterpreter.java:255)
2022-04-07 03:43:13.855 7017-7126/com.example.voicetester W/System.err:     at org.jvoicexml.interpreter.VoiceXmlInterpreterContext.interpret(VoiceXmlInterpreterContext.java:795)
2022-04-07 03:43:13.856 7017-7126/com.example.voicetester W/System.err:     at org.jvoicexml.interpreter.VoiceXmlInterpreterContext.process(VoiceXmlInterpreterContext.java:459)
2022-04-07 03:43:13.856 7017-7126/com.example.voicetester W/System.err:     at org.jvoicexml.interpreter.JVoiceXmlSession.run(JVoiceXmlSession.java:397)

**Comment by schnelle** [comment]
It seems you have your own DocumentServer implementation and the ClassCastException occurs in your class. So, I am not sure if this error relates to the JVoiceXML implementation.

**Comment by schnelle** [comment]
Closed as there was no reply for > 1 month.
