### ISSUE TITLE
Error accessing JVoiceXML in a client application

### ISSUE THREAD

**Issue by schnelle** [JVoiceXML/JVoiceXML#160]
The application is running, thank you very much. I created a simple vxml page that is running in a container on my machine. I created a client to call VoiceBrowser, pointing to my container, but when I run the client, it gives an error saying that it did not find the jndi context, "JVoiceXml".

javax.naming.NameNotFoundException: JvoiceXml
at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:134)
at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:142)
at javax.naming.InitialContext.lookup(InitialContext.java:417)
at App.getJvxml(App.java:39)
at App.main(App.java:18)
PS E:\workspaces\VoiceXML\hello_java>

==================MY CODE============================================
```
import java.net.URI;
import java.net.URISyntaxException;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;

import org.jvoicexml.ConnectionInformation;
import org.jvoicexml.JVoiceXml;
import org.jvoicexml.Session;
import org.jvoicexml.client.BasicConnectionInformation;
import org.jvoicexml.event.ErrorEvent;
import org.jvoicexml.event.JVoiceXMLEvent;

public class App {
public static void main(String[] args) throws Exception {
Context context = getContext();
JVoiceXml jvxml = getJvxml(context);
Session session = geSession(jvxml);
URI uri = getUri();

    initializeSession(session, uri);
}

private static Context getContext(){
    Context context = null;
    try{
        context = new InitialContext();
    }catch(NamingException ne){
        ne.printStackTrace();
        System.exit(-1);
    }
    return context;
}

private static JVoiceXml getJvxml(Context context){
    JVoiceXml jvxml = null;
    try{
        jvxml = (JVoiceXml)context.lookup("JVoiceXml");
    }catch(Exception ne){
        ne.printStackTrace();
        System.exit(-1);
    }
    return jvxml;
}

private static final Session geSession(JVoiceXml jvxml){
    final ConnectionInformation info = new BasicConnectionInformation("dummy", "jsapi20", "jsapi20");
    Session session = null;
    try {
        session = jvxml.createSession(info);
    } catch (ErrorEvent e) {
        e.printStackTrace();
        System.exit(-1);
    }
    return session;
}

private static final URI getUri(){
    URI uri = null;
    try{
        uri = new URI("http://localhost:8080/demo1/hello.vxml");
    }catch(URISyntaxException e){
        e.printStackTrace();
         System.exit(-1);
    }
    return uri;
}

private static void initializeSession(Session session, URI uri){
    try{
        session.call(uri);
        session.waitSessionEnd();
        session.hangup();
    }catch(JVoiceXMLEvent e){
        e.printStackTrace();
        System.exit(-1);
    }
}
}
```

===============================MY jndi.properties===========================

java.naming.factory.initial =\com.sun.jndi.rmi.registry.RegistryContextFactory
java.naming.provider.url=rmi://localhost:1099
java.naming.rmi.security.manager=true

**Comment by schnelle** [comment]
The remote name has changed but this has not been reflected in the user guide so far. Needs to be done with #141 

However, you can also see that, e.g. in https://github.com/JVoiceXML/JVoiceXML/blob/c1d8c0df394410e48600a89566fd50a100a5531c/org.jvoicexml.demo.mixedinitiativedemo/src/main/java/org/jvoicexml/demo/mixedinitiativedemo/MixedInitiativeDemo.java#L83

Please, try
```
private static JVoiceXml getJvxml(Context context){
    JVoiceXml jvxml = null;
    try{
        jvxml = (JVoiceXml)context.lookup("RemoteJVoiceXml");
    }catch(Exception ne){
        ne.printStackTrace();
        System.exit(-1);
    }
    return jvxml;
}
```

**Comment by schnelle** [comment]
Closed as there was no feedback
