### ISSUE TITLE
Invalid sound format for JSAPI 2 implementation platform

### ISSUE THREAD

**Issue by schnelle** [JVoiceXML/JVoiceXML#2]
The allocation of the JSAPI 2 implementation platform fails with 

```
2015-08-07 09:06:42,733 [JVoiceXmlMain       ] FATAL               org.jvoicexml.JVoiceXmlMain (   351) - error.noresource: line with format PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
org.jvoicexml.ConfigurationException: error.noresource: line with format PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at org.jvoicexml.implementation.jvxml.JVoiceXmlImplementationPlatformFactory.init(JVoiceXmlImplementationPlatformFactory.java:131)
	at org.jvoicexml.JVoiceXmlMain.run(JVoiceXmlMain.java:344)
Caused by: java.lang.Exception: error.noresource: line with format PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at org.jvoicexml.implementation.pool.PoolableResourceFactory.makeObject(PoolableResourceFactory.java:78)
	at org.apache.commons.pool.impl.GenericObjectPool.addObject(GenericObjectPool.java:1637)
	at org.jvoicexml.implementation.pool.KeyedResourcePool.addResourceFactory(KeyedResourcePool.java:94)
	at org.jvoicexml.implementation.jvxml.JVoiceXmlImplementationPlatformFactory.addSpokenInputFactory(JVoiceXmlImplementationPlatformFactory.java:242)
	at org.jvoicexml.implementation.jvxml.JVoiceXmlImplementationPlatformFactory.init(JVoiceXmlImplementationPlatformFactory.java:123)
	... 1 more
Caused by: org.jvoicexml.event.error.NoresourceError: error.noresource: line with format PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at org.jvoicexml.implementation.jsapi20.Jsapi20SpokenInput.open(Jsapi20SpokenInput.java:175)
	at org.jvoicexml.implementation.pool.PoolableResourceFactory.makeObject(PoolableResourceFactory.java:76)
	... 5 more
Caused by: javax.speech.AudioException: line with format PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at org.jvoicexml.jsapi2.recognition.BaseRecognizerAudioManager.handleAudioStart(BaseRecognizerAudioManager.java:189)
	at org.jvoicexml.jsapi2.BaseAudioManager.audioStart(BaseAudioManager.java:163)
	at org.jvoicexml.jsapi2.recognition.BaseRecognizer.baseAllocate(BaseRecognizer.java:534)
	at org.jvoicexml.jsapi2.BaseEngine.allocate(BaseEngine.java:285)
	at org.jvoicexml.implementation.jsapi20.Jsapi20SpokenInput.open(Jsapi20SpokenInput.java:170)
	... 6 more
```

The Sound format should be configurable to account for different environments.

**Comment by schnelle** [comment]
fixed with commit 40dd4b3e25156fb4e6b83f5d92f6e85bb0ccfb21 The capture protocol is handled within jsapi2 avoiding calls to the URL protocol handlers
