### ISSUE TITLE
Speech Grammar Special Rules: NULL, VOID, GARBAGE

### ISSUE THREAD

**Issue by rmalav15** [JVoiceXML/JVoiceXML#33]
Hey,

I see that these special tokens are mentioned in implementation [here](https://github.com/JVoiceXML/JVoiceXML/blob/facd2432e0bf4604ab90daecefe03e1c6b44976e/org.jvoicexml.xml/src/main/java/org/jvoicexml/xml/srgs/Ruleref.java#L74), But when I tried to use this special tokens in my grammar 
~~~
<rule id="choice" scope="public">
		<item>
			<item repeat="0-1"><ruleref uri="#filler"/></item>
			<ruleref special="GARBAGE"/>
			<ruleref uri="#dig2_3"/>
			<ruleref uri="#things"/>
		</item>
		<tag><![CDATA[out.count=rules.dig2_3; out.thing=rules.things;]]></tag>
	</rule>
~~~

I got the parsing error  "Ruleref is missing or has empty URI" (Because of special rule only, other were compiling okay). It looks like JvoiceXML doesnt provide support for these special rule.

Am I doing something wrong here? Can you please let me know how to handle these special rules? If there is not implementation provided with jvoiceXML, can you please let me know how to do this on my own? Any suggestion/refrence link will be very helpful?

Thanks and Regards,
Ram

**Comment by schnelle** [comment]
Which implementation platform are you using

**Comment by rmalav15** [comment]
hey Schelle,
Thank you so much for replying.

I am using the master branch only, As for platform I am using https://www.jetbrains.com/idea/ (Apologies, if that is not what you have meant by implementation platform).

Basically I am trying to run this [test](https://github.com/JVoiceXML/JVoiceXML/blob/a389efae7cd1688238b0054c0f23d756c0b5ddfa/org.jvoicexml.srgs/src/test/java/org/jvoicexml/srgs/TestMatchConsumptionSisr.java#L19), which was passing earlier. But then to check I made the above changes (basically added the GARBAGE rule) in [MediumGrammar.srgs](https://github.com/JVoiceXML/JVoiceXML/blob/a389efae7cd1688238b0054c0f23d756c0b5ddfa/org.jvoicexml.srgs/src/test/resources/MediumGrammar.srgs#L9), and I got the 
`
org.jvoicexml.srgs.SrgsSisrParsingException: Ruleref is missing or has empty URI
	at org.jvoicexml.srgs.SrgsSisrXmlGrammarParser.parseRuleref(SrgsSisrXmlGrammarParser.java:331)
	at org.jvoicexml.srgs.SrgsSisrXmlGrammarParser.parseItem(SrgsSisrXmlGrammarParser.java:231)
	at org.jvoicexml.srgs.SrgsSisrXmlGrammarParser.parseRule(SrgsSisrXmlGrammarParser.java:162)
	at org.jvoicexml.srgs.SrgsSisrXmlGrammarParser.parse(SrgsSisrXmlGrammarParser.java:145)
	at org.jvoicexml.srgs.SrgsSisrXmlGrammarParser.parse(SrgsSisrXmlGrammarParser.java:103)
	at org.jvoicexml.srgs.Utils.loadDocument(Utils.java:56)
`


Does this explanation help? Please let me know if I can use these [special rules](https://www.w3.org/TR/speech-grammar/#S2.2.3) anyhow. It will be huge help for my project.

Thanks,
Ram

**Comment by Kranberry** [comment]
Hi @schnelle,
I am currently facing this problem too, when using the special tokens. Have you by any chance been able to look at this yet?

**Comment by schnelle** [comment]
As a quick note:
I am able to reproduce the error and I am working on a fix.

**Comment by schnelle** [comment]
Added initial support for the special rules. Please check again.
